getto1:
  #是否开启wxAuth过滤器，开启了，则需要有权限设置
  enableWxAuthFilter: false
logging:
  level:
    root: info
    com.getto1: debug
spring:
  datasource:
    redis:
      host: 192.168.0.20
      port: 6379
      password:
      # 连接超时时间（毫秒）
      timeout: 1000
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  zipkin:
    base-url: http://192.168.0.12:9100
zuul:
  servlet-path: /
  sensitiveHeaders: 
  routes:
    wxqyapp-wxapi: /wxapi-api/**
    wxqyapp-oss: /oss-api/**
    wxqyapp-address-book: /addressbook-api/**
    wxqyapp-notify: /notice-api/**
    wxqyapp-comments: /comments-api/**
    wxqyapp-message: /message-api/**
    wxqyapp-party-dues: /partydues-api/**
    wxqyapp-vote: /vote-api/**
    wxqyapp-exam: /exam-api/**
    wxqyapp-partyconstruction: /partyconstruction-api/**
    wxqyapp-partyactivity: /partyactivity-api/**
    wxqyapp-knowledgewarehouse: /knowledgewarehouse-api/**
    wxqyapp-party-memberbbs: /partymemberbbs-api/**
    wxqyapp-party-openaffairs: /partyopenaffairs-api/**
    wxqyapp-suggestion: /suggestion-api/**
    wxqyapp-dailylog: /dailylog-api/**
    workflow-web: /workflow-web/**
hystrix:    
  command:   
    default: 
      execution:
        timeout:
          enabled: true 
        isolation: 
          thread: 
            timeoutInMilliseconds: 80000
ribbon: 
  ReadTimeout: 20000
  ConnectTimeout: 20000