getto1:
  uploadPath: D:/var/uploaded_files/
  #公司id  ------------------此项目该项配置可为空
  corpId: wwf5c7a11794523b01
  #当前应用id ------------------此项目该项配置可为空
  agentId: 
  #微信官方通讯录应用id ------------------此项目该项配置可为空
  wxAddressBookAgentid: 
  #当前项目访问url
  myServiceUrl: http://gsh.mynatapp.cc/oss-api/

dcsapi:
  #永中office云预览地址(每个域名对的key值不一样)
  dcsapiUrl: http://dcsapi.com/?k=366242509&url=
  #永中云office支持的预览格式
  dcsapiExt: doc,docx,xls,xlsx,ppt,pptx,txt
  #永中云office支持的文件大小(字节)
  dcsapiFileSize: 10000000
  
#fastdfs配置
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.0.13:22122
    - 192.168.0.13:22122
  pool:
    #从池中借出的对象的最大数目
    max-total: 50
    #获取连接时的最大等待毫秒数100
    max-wait-millis: 100
logging:
  level:
    root: error
    com.getto1: debug

security:
  basic:
    enabled: false

spring:
  datasource:
    basic:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.13:3306/qywxapp_basic?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: Geshihua@2018
      allowMultiQueries: true
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
    business:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.13:3306/qywxapp_oss?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: Geshihua@2018
      allowMultiQueries: true
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
  redis:
      host: 192.168.0.13
      port: 6379
      password:
      # 连接超时时间（毫秒）
      timeout: 10000
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）

  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
      include:
        mapper: /mapper-[\\w-\\.]+jar
  zipkin:
    base-url: http://192.168.0.13:9100

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*.xml
  typeAliasesPackage: com.getto1.**.domain
#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: redis